version: '3.0'
services:
  nginx-test:
    image: nginx:latest
    container_name: nginx-test
    volumes: 
      - ./public:/usr/share/nginx/html
    ports:
      - 7000:80
    restart: unless-stopped
